#%RAML 0.8
---
title: Álainn Cosmetics Item  API
version: v2
baseUri: https://alainn-item-api.cloudhub.io/{version}

traits: !include traits.raml
/items:
  description: List of all items on sale
  get:
    is: [searchable, imageable, pageable]
    responses:
      200:
        body:
          application/xml:
            example: !include get_items.xml
  /{itemId}:
    get:
      is: [imageable]
      responses:
        200:
          body:
            application/xml: 
              example: !include get_item.xml
    /stock-count:
      put:
        body:
          application/xml:
            example: !include put_item_stock_count.xml
/brands:
  description: List of brands
  get:
    is: [pageable]
    responses:
      200:
        body:
          application/xml:
            example: !include get_brands.xml
/types:
  description: List of Item types
  get:
    is: [pageable]
    responses:
      200:
        body:
          application/xml:
            example: !include get_types.xml
                            
              